export const CONFIG = {
  W: 320,
  H: 240,
  TILE: 16,
  MAP_W: 160,
  MAP_H: 20,
  PLAYER_SPEED: 1.4,
  ANIM_FPS: 8,
  TARGET_FPS: 60,
  GRAVITY: 0.4,
  JUMP: -5.5,
};

export const SCENE = {
  NONE: -1,
  INTRO: 0,
  MENU: 1,
  OPTIONS: 2,
  SAVE_SLOTS: 3,
  CHAR_SELECT: 4,
  WORLD_MAP: 5,
  TOWN: 6,
  BEACH: 7,
  PORT: 8,
  INTERIOR: 9,
  MINI_GAME: 10,
  RESULTS: 11,
  PAUSE: 12,
  NAME_INPUT: 13,
};

export const TILE = {
  AIR: 0,
  GROUND: 1,
  WALL: 2,
  PLATFORM: 3,
  WATER: 4,
  LADDER: 5,
  TRIGGER: 6,
  COLLECTIBLE: 7,
  DECORATION: 8,
  SAND: 9,
  WOOD_FLOOR: 10,
  STONE_FLOOR: 11,
  CARPET: 12,
  TILE_FLOOR: 13,
  GRASS: 14,
  BRIDGE: 15,
  ROOF: 16,
};

export const DIRECTION = {
  DOWN: 0,
  UP: 1,
  LEFT: 2,
  RIGHT: 3,
};

export const CHARACTERS = [
  {
    id: 'enoc',
    name: { de: 'Enoc', es: 'Enoc' },
    palette: {
      skin: '#d4a373',
      hair: '#1a1a1a',
      hairShadow: '#0a0a0a',
      shirt: '#1a1a1a',
      shirtShadow: '#0a0a0a',
      pants: '#2c3e7a',
      pantsShadow: '#1a2654',
      shoes: '#ffffff',
      shoesShadow: '#cccccc',
      accent: '#e87b35',
    },
  },
  {
    id: 'max',
    name: { de: 'Max', es: 'Max' },
    palette: {
      skin: '#c89878',
      hair: '#2a2a2a',
      hairShadow: '#0a0a0a',
      shirt: '#1a1a1a',
      shirtShadow: '#0a0a0a',
      pants: '#1a1a1a',
      pantsShadow: '#0a0a0a',
      shoes: '#ffffff',
      shoesShadow: '#cccccc',
      accent: '#a8a8a8',
    },
  },
  {
    id: 'vera',
    name: { de: 'Vera', es: 'Vera' },
    palette: {
      skin: '#c89060',
      hair: '#3a2418',
      hairShadow: '#1a0e08',
      shirt: '#8aa0c0',
      shirtShadow: '#5a7090',
      pants: '#2c3e7a',
      pantsShadow: '#1a2654',
      shoes: '#5a3a1a',
      shoesShadow: '#3a2410',
      accent: '#d4a04a',
    },
  },
  {
    id: 'cesar',
    name: { de: 'César', es: 'César' },
    palette: {
      skin: '#a87850',
      hair: '#2a1a0a',
      hairShadow: '#0a0500',
      shirt: '#1a1a1a',
      shirtShadow: '#0a0a0a',
      pants: '#1a1a1a',
      pantsShadow: '#0a0a0a',
      shoes: '#ffffff',
      shoesShadow: '#cccccc',
      accent: '#a0a0a0',
    },
  },
];
